version: "3.8"
services:
  nginx: # 服务名称，用户自定义
    image: nginx:latest  # 镜像版本
    ports:
      - 80:80  # 暴露端口
    volumes: # 挂载
      - /root/lbmblog/nginx/html:/usr/share/nginx/html
      - /root/lbmblog/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
  mysql:
    image: mysql:8.0.27
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - /root/mysql:/etc/mysql
    environment: # 指定用户root的密码
      - MYSQL_ROOT_PASSWORD=0507
  redis:
    ports:
      - 6379:6379
    image: redis:latest
  blog:
    image: blog:latest
    build: . # 表示以当前目录下的Dockerfile开始构建镜像
    ports:
      - 8001:8001
    depends_on: # 依赖与mysql、redis，其实可以不填，默认已经表示可以
      - mysql
      - redis