version: "3.8"
services:
  blog_app: # 服务名称，用户自定义
    image: nginx:latest  # 镜像版本
    restart: always
    ports:
      - 80:80
    volumes: # 挂载
      - /root/lbmblog/blog_app/html:/usr/share/nginx/html
      - /root/lbmblog/blog_app/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
  blog_cms: # 服务名称，用户自定义
    image: nginx:latest # 镜像版本
    restart: always #自动重启
    ports:
      - 82:82
    volumes: # 挂载
      - /root/lbmblog/blog_cms/html:/usr/share/nginx/html
      - /root/lbmblog/blog_cms/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
  blog_api:
    build: 
      context: ./blog_api
      dockerfile: Dockerfile_blog_api
    restart: always
    ports:
      - 6088:6088
  blog_admin:
    build: 
      context: ./blog_admin
      dockerfile: Dockerfile_blog_admin
    restart: always
    ports:
      - 6089:6089