FROM java:8
EXPOSE 6089
ADD blog-admin-0.0.1-SNAPSHOT.jar blog_admin.jar
RUN bash -c 'touch /blog_admin.jar'
ENTRYPOINT ["java", "-jar", "/blog_admin.jar","--spring.profiles.active=prod","--allowedOrigins=http://libomeng.cn:82"]