FROM java:8
EXPOSE 6088
ADD blog-api-0.0.1-SNAPSHOT.jar blog_api.jar
RUN bash -c 'touch /blog_api.jar'
ENTRYPOINT ["java", "-jar", "blog_api.jar","--spring.profiles.active=prod","--allowedOrigins=http://libomeng.cn"]