server:
  port: 8888

spring:
  application:
    name: lbm
  datasource:
    url: "jdbc:mysql://localhost:3307/blog?useUnicode=true&characterEncoding=utf-8"
    username: "root"
    password: "0507"
    druid:
      filters: stat,wall
      aop-patterns: 'com.lbm.*'
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: "0507"



      web-stat-filter:
        enabled: true
        url-pattern: '/*'
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          config:
            delete-allow: false
            drop-table-allow: false
  redis:
    port: 6379
    host: localhost
# datasource



mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_

qiniu:
  accessKey: Vdsp6CU6xnts94aMJkAxxAMrh8Vx3Ymxvi6FpDYg
  secretKey: Sbopp0PpVdgTxEpQefIPd3a3M16f2RFiWo-OlXwa
  url: http://r3qle33oa.hn-bkt.clouddn.com/
  bucket: lbmcc

