server:
  port: 9090
  servlet:
    context-path: "/admin"
spring:
  application:
    name: lbm
    #修改为你的数据库地址
  datasource:
    url: "" #url
    username: "" #username
    password: "" #password
    druid:
      filters: stat,wall
      aop-patterns: 'com.lbm.*'
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: "0507"
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          config:
            delete-allow: false
            drop-table-allow: false
    #修改为你的redis配置
  redis:
    host: localhost
    port: 6379
    password:  #password
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: bm_
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#图床配置,这里可以修改为你的图床
qiniu:
  accessKey: Vdsp6CU6xnts94aMJkAxxadsasdaAMrh8Vx3Ymxvi6FpDYg
  secretKey: Sbopp0PpVdgTxEpQefIPd3a3M16asdasdadf2RFiWo-OlXwa
  url: http://cdn.libomeng.cn/  #图片上传模块的图片URL前缀 上传后的图片地址为 url+uuid.jpg
  bucket: lbmcc
# 跨域访问地址
allowedOrigins: "http://localhost:8081"