server:
  port: 9090
  servlet:
    context-path: "/admin"
spring:
  application:
    name: lbm
  datasource:
    url: "jdbc:mysql://localhost:3307/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: "root"
    password: "0507"


    druid:
      filters: stat,wall
      aop-patterns: 'com.lbm.*'
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: "0507"



      web-stat-filter:
        enabled: true
        url-pattern: '/*'
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          config:
            delete-allow: false
            drop-table-allow: false

mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

qiniu:
  accessKey: Vdsp6CU6xnts94aMJkAxxAMrh8Vx3Ymxvi6FpDYg
  secretKey: Sbopp0PpVdgTxEpQefIPd3a3M16f2RFiWo-OlXwa
  url: http://r3qle33oa.hn-bkt.clouddn.com/
  bucket: lbmcc
# 跨域访问地址
allowedOrigins: "http://localhost:8666"